highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
# port: 4000
safe: true
url: ""
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /docs/
title: Jack Naimer's Resume
name: Jack Naimer
email: jacknaimer@gmail.com
email_full: mailto:jacknaimer@me.com
website: jacknaimer.com
website_full: https://jacknaimer.com
github: jackn11
# twitter: twitter
# tel: +44 0000 000000
# tel_full: tel:+440000000000
 google_maps: 'https://www.google.com/maps/search/?api=1&query=Toronto&query_place_id=ChIJpTvG15DL1IkRd8S0KlBVNTI'
address:
#  street: 44 Perth Street
#  postcode: EH3 5BL
  city: Toronto, Ontario
  country: Canada
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
